=== FMEEvangelist/FMEData/Resources/FMEUC22/Getting Started with GML, XML and Web Services/Data/DriveBC-Snapshot.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:fme="http://www.safe.com/xml/xmltables" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.safe.com/xml/xmltables" elementFormDefault="qualified">
<xs:element name="xml-tables" type="fme:xml-tablesType"/>
<xs:element name="item-table" type="fme:item-tableType"/>
<xs:element name="item" type="fme:itemType"/>
<xs:complexType name="xml-tablesType">
<xs:sequence>
<xs:element ref="fme:item-table" minOccurs="0"/>
</xs:sequence>
</xs:complexType>
<xs:complexType name="item-tableType">
<xs:sequence>
<xs:element ref="fme:item" minOccurs="0" maxOccurs="unbounded"/>
</xs:sequence>
</xs:complexType>
<xs:complexType name="itemType">
<xs:sequence>
<xs:element name="category" minOccurs="0">
<xs:simpleType>
<xs:restriction base="xs:string">
<xs:maxLength value="15"/>
</xs:restriction>
</xs:simpleType></xs:element>
<xs:element name="description" minOccurs="0">
<xs:simpleType>
<xs:restriction base="xs:string">
<xs:maxLength value="492"/>
</xs:restriction>
</xs:simpleType></xs:element>
<xs:element name="district" minOccurs="0">
<xs:simpleType>
<xs:restriction base="xs:string">
<xs:maxLength value="24"/>
</xs:restriction>
</xs:simpleType></xs:element>
<xs:element name="guid" minOccurs="0">
<xs:simpleType>
<xs:restriction base="xs:string">
<xs:maxLength value="33"/>
</xs:restriction>
</xs:simpleType></xs:element>
<xs:element name="lat" minOccurs="0">
<xs:simpleType>
<xs:restriction base="xs:decimal">
<xs:totalDigits value="9"/>
<xs:fractionDigits value="6"/>
</xs:restriction>
</xs:simpleType></xs:element>
<xs:element name="link" minOccurs="0">
<xs:simpleType>
<xs:restriction base="xs:string">
<xs:maxLength value="33"/>
</xs:restriction>
</xs:simpleType></xs:element>
<xs:element name="long" minOccurs="0">
<xs:simpleType>
<xs:restriction base="xs:decimal">
<xs:totalDigits value="11"/>
<xs:fractionDigits value="6"/>
</xs:restriction>
</xs:simpleType></xs:element>
<xs:element name="pubDate" minOccurs="0">
<xs:simpleType>
<xs:restriction base="xs:string">
<xs:maxLength value="32"/>
</xs:restriction>
</xs:simpleType></xs:element>
<xs:element name="route" minOccurs="0">
<xs:simpleType>
<xs:restriction base="xs:string">
<xs:maxLength value="22"/>
</xs:restriction>
</xs:simpleType></xs:element>
<xs:element name="severity" minOccurs="0">
<xs:simpleType>
<xs:restriction base="xs:string">
<xs:maxLength value="7"/>
</xs:restriction>
</xs:simpleType></xs:element>
<xs:element name="title" minOccurs="0">
<xs:simpleType>
<xs:restriction base="xs:string">
<xs:maxLength value="48"/>
</xs:restriction>
</xs:simpleType></xs:element>
<xs:element name="type" minOccurs="0">
<xs:simpleType>
<xs:restriction base="xs:string">
<xs:maxLength value="16"/>
</xs:restriction>
</xs:simpleType></xs:element>
<xs:any minOccurs="0" processContents="lax"/>
<xs:element name="xml_id" minOccurs="0">
<xs:simpleType>
<xs:restriction base="xs:string">
<xs:maxLength value="15"/>
</xs:restriction>
</xs:simpleType></xs:element>
<xs:element name="xml_matched_element" minOccurs="0">
<xs:simpleType>
<xs:restriction base="xs:string">
<xs:maxLength value="5"/>
</xs:restriction>
</xs:simpleType></xs:element>
<xs:element name="xml_parent_child_pos" minOccurs="0">
<xs:simpleType>
<xs:restriction base="xs:string">
<xs:maxLength value="1"/>
</xs:restriction>
</xs:simpleType></xs:element>
<xs:element name="xml_parent_id" minOccurs="0">
<xs:simpleType>
<xs:restriction base="xs:string">
<xs:maxLength value="1"/>
</xs:restriction>
</xs:simpleType></xs:element>
</xs:sequence>
</xs:complexType>
</xs:schema>

=== FMEEvangelist/FMEData/Resources/FMEUC22/Getting Started with GML, XML and Web Services/Data/DriveBC-Snapshot.xml
<?xml version="1.0" encoding="UTF-8"?>
<fme:xml-tables xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:fme="http://www.safe.com/xml/xmltables" xsi:schemaLocation="http://www.safe.com/xml/xmltables DriveBC-Snapshot.xsd">
<fme:item-table>
<fme:item>
<fme:category>CONSTRUCTION</fme:category>
<fme:description>Highway 17, in both directions. Utility work between 136 St and 104 Ave for 2.2 km (Surrey). Until Mon Nov 30 at 5:00 AM PST. From 12:00 AM to 12:00 AM PST on weekends and from 7:00 PM to 5:00 AM PST on weekdays. Right lane closed. Watch for traffic control. Next update time Mon Nov 30 at 5:00 AM PST. Last updated Tue Nov 3 at 1:54 PM PST. (DBC-23589)</fme:description>
<fme:district>Lower Mainland District</fme:district>
<fme:guid>http://drivebc.ca/~DBC-23589</fme:guid>
<fme:lat>49.211927</fme:lat>
<fme:link>http://drivebc.ca/~DBC-23589</fme:link>
<fme:long>-122.795109</fme:long>
<fme:pubDate>Tue, 03 Nov 2020 13:54:34 -0800</fme:pubDate>
<fme:route>Highway 17</fme:route>
<fme:severity>Major</fme:severity>
<fme:title>Highway 17 - Both Directions - Current Planned</fme:title>
<fme:type>Current Planned</fme:type>
<item>
<title>Highway 17 - Both Directions - Current Planned</title>
<link>http://drivebc.ca/~DBC-23589</link>
<guid>http://drivebc.ca/~DBC-23589</guid>
<description>Highway 17, in both directions. Utility work between 136 St and 104 Ave for 2.2 km (Surrey). Until Mon Nov 30 at 5:00 AM PST. From 12:00 AM to 12:00 AM PST on weekends and from 7:00 PM to 5:00 AM PST on weekdays. Right lane closed. Watch for traffic control. Next update time Mon Nov 30 at 5:00 AM PST. Last updated Tue Nov 3 at 1:54 PM PST. (DBC-23589)</description>
<category>CONSTRUCTION</category>
<pubDate>Tue, 03 Nov 2020 13:54:34 -0800</pubDate>
<dbc:district xmlns:dbc="http://drivebc.ca/rss">Lower Mainland District</dbc:district>
<dbc:route xmlns:dbc="http://drivebc.ca/rss">Highway 17</dbc:route>
<dbc:type xmlns:dbc="http://drivebc.ca/rss">Current Planned</dbc:type>
<dbc:severity xmlns:dbc="http://drivebc.ca/rss">Major</dbc:severity>
<geo:lat xmlns:geo="http://www.w3.org/2003/01/geo/wgs84_pos#">49.211927</geo:lat>
<geo:long xmlns:geo="http://www.w3.org/2003/01/geo/wgs84_pos#">-122.795109</geo:long>
</item>
<fme:xml_id>id-item-1.1.5</fme:xml_id>
<fme:xml_matched_element>item</fme:xml_matched_element>
<fme:xml_parent_child_pos/>
<fme:xml_parent_id/>
</fme:item>
<fme:item>
<fme:category>CONSTRUCTION</fme:category>
<fme:description>Highway 17, in both directions. Construction work between 136 St and 104 Ave for 0.1 km (Surrey). Until Mon Nov 30. From 7:00 PM to 5:00 AM PST on weekdays and Sunday. Lane Closure. Expect delays, plan your route ahead, please slow down, follow the lowered speed limits of 60km/hr during the day and 40km/hr at night in construction zone. Obey traffic control. Next update time Mon Nov 30 at 5:00 AM PST. Last updated Tue Nov 3 at 1:55 PM PST. (DBC-21199)</fme:description>
<fme:district>Lower Mainland District</fme:district>
<fme:guid>http://drivebc.ca/~DBC-21199</fme:guid>
<fme:lat>49.213027</fme:lat>
<fme:link>http://drivebc.ca/~DBC-21199</fme:link>
<fme:long>-122.802092</fme:long>
<fme:pubDate>Tue, 03 Nov 2020 13:55:44 -0800</fme:pubDate>
<fme:route>Highway 17</fme:route>
<fme:severity>Major</fme:severity>
<fme:title>Highway 17 - Both Directions - Current Planned</fme:title>
<fme:type>Current Planned</fme:type>
<item>
<title>Highway 17 - Both Directions - Current Planned</title>
<link>http://drivebc.ca/~DBC-21199</link>
<guid>http://drivebc.ca/~DBC-21199</guid>
<description>Highway 17, in both directions. Construction work between 136 St and 104 Ave for 0.1 km (Surrey). Until Mon Nov 30. From 7:00 PM to 5:00 AM PST on weekdays and Sunday. Lane Closure. Expect delays, plan your route ahead, please slow down, follow the lowered speed limits of 60km/hr during the day and 40km/hr at night in construction zone. Obey traffic control. Next update time Mon Nov 30 at 5:00 AM PST. Last updated Tue Nov 3 at 1:55 PM PST. (DBC-21199)</description>
<category>CONSTRUCTION</category>
<pubDate>Tue, 03 Nov 2020 13:55:44 -0800</pubDate>
<dbc:district xmlns:dbc="http://drivebc.ca/rss">Lower Mainland District</dbc:district>
<dbc:route xmlns:dbc="http://drivebc.ca/rss">Highway 17</dbc:route>
<dbc:type xmlns:dbc="http://drivebc.ca/rss">Current Planned</dbc:type>
<dbc:severity xmlns:dbc="http://drivebc.ca/rss">Major</dbc:severity>
<geo:lat xmlns:geo="http://www.w3.org/2003/01/geo/wgs84_pos#">49.213027</geo:lat>
<geo:long xmlns:geo="http://www.w3.org/2003/01/geo/wgs84_pos#">-122.802092</geo:long>
</item>
<fme:xml_id>id-item-1.1.6</fme:xml_id>
<fme:xml_matched_element>item</fme:xml_matched_element>
<fme:xml_parent_child_pos/>
<fme:xml_parent_id/>
</fme:item>
<fme:item>
<fme:category>CONSTRUCTION</fme:category>
<fme:description>Highway 99, in both directions. Construction work at Massey Tunnel (Richmond). Until Sun Mar 28, 2021. From 10:00 PM to 5:00 AM PST on weekdays. Replacing the tunnel roadway joints and electrical system. The SB tube will be closed during work times. Traffic counter flow to single lane traffic in the NB tube. Next update time Mon Nov 30 at 10:00 AM PST. Last updated Tue Nov 3 at 10:04 AM PST. (DBC-21852)</fme:description>
<fme:district>Lower Mainland District</fme:district>
<fme:guid>http://drivebc.ca/~DBC-21852</fme:guid>
<fme:lat>49.122077</fme:lat>
<fme:link>http://drivebc.ca/~DBC-21852</fme:link>
<fme:long>-123.075822</fme:long>
<fme:pubDate>Tue, 03 Nov 2020 10:04:03 -0800</fme:pubDate>
<fme:route>Highway 99</fme:route>
<fme:severity>Major</fme:severity>
<fme:title>Highway 99 - Both Directions - Current Planned</fme:title>
<fme:type>Current Planned</fme:type>
<item>
<title>Highway 99 - Both Directions - Current Planned</title>
<link>http://drivebc.ca/~DBC-21852</link>
<guid>http://drivebc.ca/~DBC-21852</guid>
<description>Highway 99, in both directions. Construction work at Massey Tunnel (Richmond). Until Sun Mar 28, 2021. From 10:00 PM to 5:00 AM PST on weekdays. Replacing the tunnel roadway joints and electrical system. The SB tube will be closed during work times. Traffic counter flow to single lane traffic in the NB tube. Next update time Mon Nov 30 at 10:00 AM PST. Last updated Tue Nov 3 at 10:04 AM PST. (DBC-21852)</description>
<category>CONSTRUCTION</category>
<pubDate>Tue, 03 Nov 2020 10:04:03 -0800</pubDate>
<dbc:district xmlns:dbc="http://drivebc.ca/rss">Lower Mainland District</dbc:district>
<dbc:route xmlns:dbc="http://drivebc.ca/rss">Highway 99</dbc:route>
<dbc:type xmlns:dbc="http://drivebc.ca/rss">Current Planned</dbc:type>
<dbc:severity xmlns:dbc="http://drivebc.ca/rss">Major</dbc:severity>
<geo:lat xmlns:geo="http://www.w3.org/2003/01/geo/wgs84_pos#">49.122077</geo:lat>
<geo:long xmlns:geo="http://www.w3.org/2003/01/geo/wgs84_pos#">-123.075822</geo:long>
</item>
<fme:xml_id>id-item-1.1.7</fme:xml_id>
<fme:xml_matched_element>item</fme:xml_matched_element>
<fme:xml_parent_child_pos/>
<fme:xml_parent_id/>
</fme:item>
<fme:item>
<fme:category>INCIDENT</fme:category>
<fme:description>Barnston Island Ferry. Travel advisory in effect at Barnston Island. Passengers asked to remain inside vehicles during sailings. Walk-on passengers and cyclists are limited to ensure physical distancing. Last updated Mon Jul 20 at 8:22 AM PDT. (DBC-16715)</fme:description>
<fme:district>Lower Mainland District</fme:district>
<fme:guid>http://drivebc.ca/~DBC-16715</fme:guid>
<fme:lat>49.192245</fme:lat>
<fme:link>http://drivebc.ca/~DBC-16715</fme:link>
<fme:long>-122.723534</fme:long>
<fme:pubDate>Mon, 20 Jul 2020 08:22:41 -0800</fme:pubDate>
<fme:route>Barnston Island Ferry</fme:route>
<fme:severity>Normal</fme:severity>
<fme:title>Barnston Island Ferry - Incident</fme:title>
<fme:type>Incident</fme:type>
<item>
<title>Barnston Island Ferry - Incident</title>
<link>http://drivebc.ca/~DBC-16715</link>
<guid>http://drivebc.ca/~DBC-16715</guid>
<description>Barnston Island Ferry. Travel advisory in effect at Barnston Island. Passengers asked to remain inside vehicles during sailings. Walk-on passengers and cyclists are limited to ensure physical distancing. Last updated Mon Jul 20 at 8:22 AM PDT. (DBC-16715)</description>
<category>INCIDENT</category>
<pubDate>Mon, 20 Jul 2020 08:22:41 -0800</pubDate>
<dbc:district xmlns:dbc="http://drivebc.ca/rss">Lower Mainland District</dbc:district>
<dbc:route xmlns:dbc="http://drivebc.ca/rss">Barnston Island Ferry</dbc:route>
<dbc:type xmlns:dbc="http://drivebc.ca/rss">Incident</dbc:type>
<dbc:severity xmlns:dbc="http://drivebc.ca/rss">Normal</dbc:severity>
<geo:lat xmlns:geo="http://www.w3.org/2003/01/geo/wgs84_pos#">49.192245</geo:lat>
<geo:long xmlns:geo="http://www.w3.org/2003/01/geo/wgs84_pos#">-122.723534</geo:long>
</item>
<fme:xml_id>id-item-1.1.8</fme:xml_id>
<fme:xml_matched_element>item</fme:xml_matched_element>
<fme:xml_parent_child_pos/>
<fme:xml_parent_id/>
</fme:item>
<fme:item>
<fme:category>INCIDENT</fme:category>
<fme:description>Barnston Island Ferry. Travel advisory in effect at Barnston Island. By order of the Provincial Health Officer, individuals and businesses in the Lower Mainland and Fraser Valley must significantly reduce social interactions and travel. Next update time Mon Nov 23 at 12:00 PM PST. Last updated Tue Nov 10 at 11:00 AM PST. (DBC-23770)</fme:description>
<fme:district>Lower Mainland District</fme:district>
<fme:guid>http://drivebc.ca/~DBC-23770</fme:guid>
<fme:lat>49.192164</fme:lat>
<fme:link>http://drivebc.ca/~DBC-23770</fme:link>
<fme:long>-122.724839</fme:long>
<fme:pubDate>Tue, 10 Nov 2020 11:00:29 -0800</fme:pubDate>
<fme:route>Barnston Island Ferry</fme:route>
<fme:severity>Normal</fme:severity>
<fme:title>Barnston Island Ferry - Incident</fme:title>
<fme:type>Incident</fme:type>
<item>
<title>Barnston Island Ferry - Incident</title>
<link>http://drivebc.ca/~DBC-23770</link>
<guid>http://drivebc.ca/~DBC-23770</guid>
